### ISSUE TITLE
Repeating argument in a template

### ISSUE THREAD

**Issue by OriShapira** [vered1986/OKR#16] opened 2017-08-15 07:35 UTC
In the partial boy_scouts event (json attached), the proposition P3 has a template "{a.1} {a.3} {a.1} to be released".
An argument ID shouldn't repeat in a template (since each has its own role) even if their assigned concept are the same.

[Boy_scouts.json.txt](https://github.com/vered1986/OKR/files/1224381/Boy_scouts.json.txt)

**Comment by gabrielStanovsky** [comment] 2017-08-15 07:46
@OriShapira, Can you specify in which sentence this happens?

**Comment by OriShapira** [comment] 2017-08-15 07:48
In tweet 258795112623116288:
"Boy Scouts files on alleged sex abusers to be released -".

**Comment by gabrielStanovsky** [comment] 2017-08-15 07:54
I don't think it's a bug in the PropS wrapper. 
This is what I get from running it as a single sentence (note the template doesn't repeat arguments):
```
{'Entities': {'A1': ('Boy Scouts files on alleged sex abusers to be released -',
                     (0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10)),
              'A2': ('alleged sex abusers', (4, 5, 6)),
              'A3': ('on', (3,))},
 'Predicates': {'P1': {'Arguments': ['A1', 'A2', 'A3'],
                       'Bare predicate': ('to be released', (7, 8, 9)),
                       'Head': {'Lemma': u'release',
                                'POS': 'VBN',
                                'Surface': ('released', [9])},
                       'Template': '{A1} {A3} {A2} to be released'}},
 'Sentence': 'Boy Scouts files on alleged sex abusers to be released -'}
```

**Comment by OriShapira** [comment] 2017-08-15 08:04
Maybe A1 should be something like "Boy Scouts files", so that the template '{A1} {A3} {A2} to be released' would make more sense.
@kleinay, is this what might be causing the JSON generator to unexpectedly use A1 twice?

**Comment by gabrielStanovsky** [comment] 2017-08-15 08:16
Side note - if I run the PW on a cleaner version of the sentence (replacing the dash at the end with a full stop), I get something slightly saner (see below). 
Maybe we should consider a cleaning phase for the tweets to remove this kind of noise that messes up automatic parsers.
```
{'Entities': {'A1': ('alleged sex abusers', (4, 5, 6)),
              'A2': ('Boy Scouts', (0, 1))},
 'Predicates': {'P1': {'Arguments': ['A1', 'A2', 'P2'],
                       'Bare predicate': ('files on', (2, 3)),
                       'Head': {'Lemma': u'file',
                                'POS': 'VBZ',
                                'Surface': ('files', [2])},
                       'Template': '{A2} files on {A1} {P2}'},
                'P2': {'Arguments': ['A2'],
                       'Bare predicate': ('to be released', (7, 8, 9)),
                       'Head': {'Lemma': u'release',
                                'POS': 'VBN',
                                'Surface': ('released', [9])},
                       'Template': '{A2} to be released'}},
 'Sentence': 'Boy Scouts files on alleged sex abusers to be released .'}
```

**Comment by gabrielStanovsky** [comment] 2017-08-15 08:33
Okay, I introduced a small fix, this looks better now on my side (see below).
The "on" error is from wrong underlying parsing, caused by the dash at the end.
@kleinay, after you merge the PR we can test if the issue of repeating arguments is also resolved.

```
{'Entities': {'A1': ('Boy Scouts files', (0, 1, 2)),
              'A2': ('sex abusers', (5, 6)),
              'A3': ('on', (3,))},
 'Predicates': {'P1': {'Arguments': ['A1', 'A2', 'A3'],
                       'Bare predicate': ('to be released', (7, 8, 9)),
                       'Head': {'Lemma': u'release',
                                'POS': 'VBN',
                                'Surface': ('released', [9])},
                       'Template': '{A1} {A3} {A2} to be released'}},
 'Sentence': 'Boy Scouts files on alleged sex abusers to be released -'}
```

**Comment by kleinay** [comment] 2017-08-15 21:06
Following Gabi's fixes, I cannot see if the problem persist - The example-tweet is not making a duplicate-argument template anymore, but this is still in principal a possible scnerio. @OriShapira , please update if you can see the same problem anywhere after the fix.

**Comment by kleinay** [comment] 2017-08-15 21:16
In principal, the scenerio of duplicated argument-slots in same template is currently possible, due to the fact that the argument-aligment algorithm we use is trivial - we assign all argument-mention refering to the same concept to the same argument slot (i.e proposition-level argument - denoted by a.1, a.2 etc.). Thus, in predicates where two argument refer the same concept (e.g. "Bob picture himself"), the template would contain the same argument slot ("a.1 picture a.1"), which is forbidden. 
I commited a fix to handle this scenrio explicitly.  @OriShapira , if you encounter this problem, we would run the auto-pipeline again with the fix to verify it solves the problem.

**Comment by OriShapira** [comment] 2017-11-02 11:02
This sentence
"Buddhists and Muslims raping and killing each other."
outputs:
'{A2} {A1} {A1} killing {A3}'
and it's left in the output JSON.

Thanks.

**Comment by kleinay** [comment] 2017-11-02 13:08
this is fixed now I think, @OriShapira  try to create summarization please.

**Closed as completed** 2017-12-06 09:17 UTC
Labels: bug
